// Code generated by goyacc -p phi -o parser/parser.y.go parser/parser.y. DO NOT EDIT.

// Run this after each change:
// goyacc -p phi -o parser/parser.y.go parser/parser.y
//
//line parser/parser.y:2
package parser

import __yyfmt__ "fmt"

//line parser/parser.y:4

import (
	"io"
	"phi/process"
	"phi/types"
)

//line parser/parser.y:14
type phiSymType struct {
	yys            int
	strval         string
	common_type    unexpandedProcessOrFunction
	statements     []unexpandedProcessOrFunction
	name           process.Name
	names          []process.Name
	form           process.Form
	branches       []*process.BranchForm
	sessionType    types.SessionType
	sessionTypeAlt []types.BranchOption
	polarity       types.Polarity
}

const LABEL = 57346
const LEFT_ARROW = 57347
const RIGHT_ARROW = 57348
const EQUALS = 57349
const DOT = 57350
const SEQUENCE = 57351
const COLON = 57352
const COMMA = 57353
const LPAREN = 57354
const RPAREN = 57355
const LSBRACK = 57356
const RSBRACK = 57357
const LANGLE = 57358
const RANGLE = 57359
const PIPE = 57360
const SEND = 57361
const RECEIVE = 57362
const CASE = 57363
const CLOSE = 57364
const WAIT = 57365
const CAST = 57366
const SHIFT = 57367
const ACCEPT = 57368
const ACQUIRE = 57369
const DETACH = 57370
const RELEASE = 57371
const DROP = 57372
const SPLIT = 57373
const PUSH = 57374
const NEW = 57375
const SNEW = 57376
const TYPE = 57377
const LET = 57378
const IN = 57379
const END = 57380
const SPRC = 57381
const PRC = 57382
const FORWARD = 57383
const SELF = 57384
const PRINT = 57385
const PLUS = 57386
const MINUS = 57387
const TIMES = 57388
const AMPERSAND = 57389
const UNIT = 57390
const LCBRACK = 57391
const RCBRACK = 57392
const LOLLI = 57393
const PERCENTAGE = 57394
const ASSUMING = 57395
const EXEC = 57396

var phiToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LABEL",
	"LEFT_ARROW",
	"RIGHT_ARROW",
	"EQUALS",
	"DOT",
	"SEQUENCE",
	"COLON",
	"COMMA",
	"LPAREN",
	"RPAREN",
	"LSBRACK",
	"RSBRACK",
	"LANGLE",
	"RANGLE",
	"PIPE",
	"SEND",
	"RECEIVE",
	"CASE",
	"CLOSE",
	"WAIT",
	"CAST",
	"SHIFT",
	"ACCEPT",
	"ACQUIRE",
	"DETACH",
	"RELEASE",
	"DROP",
	"SPLIT",
	"PUSH",
	"NEW",
	"SNEW",
	"TYPE",
	"LET",
	"IN",
	"END",
	"SPRC",
	"PRC",
	"FORWARD",
	"SELF",
	"PRINT",
	"PLUS",
	"MINUS",
	"TIMES",
	"AMPERSAND",
	"UNIT",
	"LCBRACK",
	"RCBRACK",
	"LOLLI",
	"PERCENTAGE",
	"ASSUMING",
	"EXEC",
}

var phiStatenames = [...]string{}

const phiEofCode = 1
const phiErrCode = 2
const phiInitialStackSize = 16

//line parser/parser.y:243

// Parse is the entry point to the parser.
func Parse(r io.Reader) (allEnvironment, error) {
	l := newLexer(r)
	phiParse(l)
	allEnvironment := allEnvironment{}
	select {
	case err := <-l.Errors:
		return allEnvironment, err
	default:
		// allEnvironment := l
		allEnvironment.procsAndFuns = l.processesOrFunctionsRes
		return allEnvironment, nil
	}
}

//line yacctab:1
var phiExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const phiPrivate = 57344

const phiLast = 297

var phiAct = [...]uint8{
	3, 138, 150, 57, 117, 84, 10, 166, 74, 28,
	27, 56, 199, 68, 26, 164, 185, 46, 197, 152,
	101, 102, 105, 134, 141, 104, 103, 29, 30, 59,
	32, 163, 7, 97, 24, 25, 205, 60, 31, 33,
	181, 36, 65, 192, 41, 42, 43, 44, 45, 180,
	47, 102, 176, 102, 102, 102, 103, 102, 103, 103,
	103, 102, 103, 177, 175, 96, 103, 131, 23, 24,
	25, 75, 132, 77, 156, 78, 24, 25, 39, 144,
	111, 69, 113, 126, 114, 109, 85, 106, 133, 73,
	118, 95, 66, 201, 93, 94, 80, 61, 129, 98,
	64, 121, 120, 172, 122, 115, 53, 140, 135, 75,
	110, 24, 25, 112, 142, 40, 136, 137, 86, 124,
	87, 71, 147, 153, 72, 70, 148, 143, 127, 157,
	123, 159, 4, 107, 82, 162, 37, 91, 38, 151,
	152, 85, 76, 67, 169, 149, 167, 170, 165, 85,
	125, 48, 49, 50, 51, 52, 118, 174, 154, 179,
	168, 171, 178, 116, 183, 173, 161, 108, 145, 89,
	186, 146, 213, 62, 90, 203, 189, 202, 196, 184,
	182, 158, 130, 195, 187, 128, 198, 83, 81, 200,
	79, 35, 210, 214, 34, 206, 188, 207, 88, 208,
	209, 194, 155, 211, 212, 139, 58, 160, 119, 190,
	191, 215, 9, 193, 216, 217, 100, 92, 63, 55,
	16, 54, 2, 1, 6, 204, 99, 5, 22, 8,
	11, 13, 14, 21, 20, 19, 18, 0, 15, 0,
	0, 0, 0, 28, 27, 0, 0, 0, 26, 12,
	23, 17, 24, 25, 0, 9, 0, 0, 0, 0,
	0, 29, 30, 16, 0, 0, 0, 6, 0, 0,
	5, 0, 8, 11, 13, 14, 0, 0, 0, 0,
	0, 15, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 12, 23, 17, 24, 25,
}

var phiPact = [...]int16{
	208, -1000, -1000, -1000, -1000, 26, 26, 186, 26, 126,
	74, 26, 26, 26, 26, 26, 251, 26, -26, -26,
	-26, -26, -26, -1000, -1000, -1000, 92, 217, 215, 202,
	25, 81, -1000, 162, 214, 67, 131, 77, 26, 130,
	26, -1000, 26, 181, 80, 179, 121, 178, -1000, -1000,
	-1000, -1000, -1000, 26, 106, 191, -1000, 158, 164, 125,
	213, 26, 26, 75, 251, 0, 26, 212, 15, -1000,
	-1000, -24, -27, 77, 120, 156, 26, 26, -1000, 251,
	26, 251, -1000, 251, 90, 152, 202, 204, 77, 202,
	77, 117, 107, 139, 66, 26, 176, 251, 173, 54,
	72, -10, 77, 77, 201, 201, 11, -1000, 26, 114,
	-1000, -1000, 62, -1000, -1000, 161, 26, 113, 134, 129,
	-25, -1000, -25, -1000, 110, 26, 197, 57, 251, 172,
	251, -1000, 203, 26, 251, -2, -25, -25, -35, 138,
	-43, -1000, -1000, -1000, -1000, 251, 77, -1000, 137, 202,
	88, 77, 202, -1000, 47, 32, -1000, -1000, 251, -1000,
	33, 23, 171, 251, -1000, 77, -1000, -1000, 9, 251,
	77, -1000, 189, 8, -1000, -1000, 26, 26, 12, -1000,
	26, 195, 251, 169, 7, 251, -1000, 5, 251, 78,
	168, 166, 26, 19, 251, -1000, 251, 201, -1000, 251,
	-1000, 185, 251, 251, 163, 187, -1000, -1000, -1000, -1000,
	251, -1000, -1000, 251, 251, -1000, -1000, -1000,
}

var phiPgo = [...]uint8{
	0, 132, 236, 235, 234, 233, 228, 0, 32, 3,
	5, 8, 4, 2, 11, 226, 13, 1, 6, 223,
	222,
}

var phiR1 = [...]int8{
	0, 19, 20, 20, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 2, 2, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 15, 15, 15,
	10, 10, 11, 11, 11, 12, 12, 12, 13, 13,
	14, 14, 9, 9, 8, 8, 5, 3, 3, 3,
	3, 4, 16, 16, 16, 16, 16, 16, 16, 17,
	17, 18, 18, 6, 6,
}

var phiR2 = [...]int8{
	0, 1, 1, 1, 1, 2, 1, 2, 1, 2,
	1, 2, 1, 2, 6, 8, 7, 10, 6, 5,
	6, 8, 7, 9, 4, 5, 2, 3, 4, 10,
	11, 4, 5, 6, 4, 3, 4, 0, 6, 8,
	1, 3, 0, 1, 3, 0, 1, 3, 0, 2,
	1, 3, 1, 3, 1, 1, 2, 7, 9, 8,
	10, 4, 1, 1, 4, 4, 3, 3, 3, 3,
	5, 1, 1, 4, 5,
}

var phiChk = [...]int16{
	-1000, -19, -20, -7, -1, 19, 16, -8, 21, 4,
	-18, 22, 41, 23, 24, 30, 12, 43, -2, -3,
	-4, -5, -6, 42, 44, 45, 40, 36, 35, 53,
	54, -8, 4, -8, 8, 5, -8, 10, 12, 4,
	41, -8, -8, -8, -8, -8, -7, -8, -1, -1,
	-1, -1, -1, 14, 4, 4, -14, -9, 4, 4,
	-18, 16, 11, 4, 33, -18, 25, 12, -16, 4,
	48, 44, 47, 12, -11, -8, 12, -8, -8, 9,
	16, 9, 13, 9, -10, -8, 12, 14, 7, 11,
	10, 12, 4, -8, -8, 16, -7, 33, -8, -15,
	4, 5, 46, 51, 49, 49, -16, 13, 11, -11,
	-8, -7, -8, -7, -7, 15, 11, -12, -9, 4,
	-16, -14, -16, 13, 12, 11, 17, -8, 9, -7,
	9, 13, 18, 16, 33, -18, -16, -16, -17, 4,
	-17, 13, -10, 13, 17, 7, 10, -10, 13, 11,
	-13, 10, 11, 13, -8, 5, 17, -7, 9, -7,
	4, -8, -7, 33, 50, 10, 50, -7, -16, 7,
	10, -14, 15, -16, -12, 17, 20, 31, -18, -7,
	16, 17, 9, -7, -16, 7, -7, -16, 7, -13,
	-8, -8, 31, -8, 6, -7, 9, 11, -7, 7,
	-7, 15, 9, 9, -8, 17, -7, -7, -17, -7,
	7, -7, -7, 9, 6, -7, -7, -7,
}

var phiDef = [...]int8{
	0, -2, 1, 2, 3, 0, 0, 0, 0, 55,
	0, 0, 0, 0, 0, 0, 0, 0, 4, 6,
	8, 10, 12, 54, 71, 72, 0, 0, 0, 0,
	0, 0, 55, 0, 0, 0, 0, 0, 42, 0,
	0, 26, 0, 0, 0, 0, 0, 0, 5, 7,
	9, 11, 13, 0, 0, 0, 56, 50, 52, 0,
	0, 0, 0, 0, 0, 0, 0, 37, 0, 62,
	63, 0, 0, 0, 0, 43, 42, 0, 27, 0,
	0, 0, 35, 0, 0, 40, 45, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 24, 0, 0,
	28, 31, 0, 34, 36, 0, 0, 0, 46, 48,
	61, 51, 53, 73, 0, 0, 0, 0, 0, 0,
	0, 19, 0, 0, 0, 0, 66, 67, 0, 0,
	0, 68, 44, 25, 32, 0, 0, 41, 0, 0,
	0, 0, 45, 74, 0, 0, 18, 20, 0, 33,
	0, 0, 0, 0, 64, 0, 65, 14, 0, 0,
	0, 47, 0, 48, 49, 16, 0, 0, 0, 22,
	0, 0, 0, 0, 69, 0, 57, 0, 0, 0,
	0, 0, 0, 0, 0, 21, 0, 0, 15, 0,
	59, 0, 0, 0, 0, 0, 38, 23, 70, 58,
	0, 17, 29, 0, 0, 60, 30, 39,
}

var phiTok1 = [...]int8{
	1,
}

var phiTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54,
}

var phiTok3 = [...]int8{
	0,
}

var phiErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	phiDebug        = 0
	phiErrorVerbose = false
)

type phiLexer interface {
	Lex(lval *phiSymType) int
	Error(s string)
}

type phiParser interface {
	Parse(phiLexer) int
	Lookahead() int
}

type phiParserImpl struct {
	lval  phiSymType
	stack [phiInitialStackSize]phiSymType
	char  int
}

func (p *phiParserImpl) Lookahead() int {
	return p.char
}

func phiNewParser() phiParser {
	return &phiParserImpl{}
}

const phiFlag = -1000

func phiTokname(c int) string {
	if c >= 1 && c-1 < len(phiToknames) {
		if phiToknames[c-1] != "" {
			return phiToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func phiStatname(s int) string {
	if s >= 0 && s < len(phiStatenames) {
		if phiStatenames[s] != "" {
			return phiStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func phiErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !phiErrorVerbose {
		return "syntax error"
	}

	for _, e := range phiErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + phiTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(phiPact[state])
	for tok := TOKSTART; tok-1 < len(phiToknames); tok++ {
		if n := base + tok; n >= 0 && n < phiLast && int(phiChk[int(phiAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if phiDef[state] == -2 {
		i := 0
		for phiExca[i] != -1 || int(phiExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; phiExca[i] >= 0; i += 2 {
			tok := int(phiExca[i])
			if tok < TOKSTART || phiExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if phiExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += phiTokname(tok)
	}
	return res
}

func philex1(lex phiLexer, lval *phiSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(phiTok1[0])
		goto out
	}
	if char < len(phiTok1) {
		token = int(phiTok1[char])
		goto out
	}
	if char >= phiPrivate {
		if char < phiPrivate+len(phiTok2) {
			token = int(phiTok2[char-phiPrivate])
			goto out
		}
	}
	for i := 0; i < len(phiTok3); i += 2 {
		token = int(phiTok3[i+0])
		if token == char {
			token = int(phiTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(phiTok2[1]) /* unknown char */
	}
	if phiDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", phiTokname(token), uint(char))
	}
	return char, token
}

func phiParse(philex phiLexer) int {
	return phiNewParser().Parse(philex)
}

func (phircvr *phiParserImpl) Parse(philex phiLexer) int {
	var phin int
	var phiVAL phiSymType
	var phiDollar []phiSymType
	_ = phiDollar // silence set and not used
	phiS := phircvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	phistate := 0
	phircvr.char = -1
	phitoken := -1 // phircvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		phistate = -1
		phircvr.char = -1
		phitoken = -1
	}()
	phip := -1
	goto phistack

ret0:
	return 0

ret1:
	return 1

phistack:
	/* put a state and value onto the stack */
	if phiDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", phiTokname(phitoken), phiStatname(phistate))
	}

	phip++
	if phip >= len(phiS) {
		nyys := make([]phiSymType, len(phiS)*2)
		copy(nyys, phiS)
		phiS = nyys
	}
	phiS[phip] = phiVAL
	phiS[phip].yys = phistate

phinewstate:
	phin = int(phiPact[phistate])
	if phin <= phiFlag {
		goto phidefault /* simple state */
	}
	if phircvr.char < 0 {
		phircvr.char, phitoken = philex1(philex, &phircvr.lval)
	}
	phin += phitoken
	if phin < 0 || phin >= phiLast {
		goto phidefault
	}
	phin = int(phiAct[phin])
	if int(phiChk[phin]) == phitoken { /* valid shift */
		phircvr.char = -1
		phitoken = -1
		phiVAL = phircvr.lval
		phistate = phin
		if Errflag > 0 {
			Errflag--
		}
		goto phistack
	}

phidefault:
	/* default state action */
	phin = int(phiDef[phistate])
	if phin == -2 {
		if phircvr.char < 0 {
			phircvr.char, phitoken = philex1(philex, &phircvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if phiExca[xi+0] == -1 && int(phiExca[xi+1]) == phistate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			phin = int(phiExca[xi+0])
			if phin < 0 || phin == phitoken {
				break
			}
		}
		phin = int(phiExca[xi+1])
		if phin < 0 {
			goto ret0
		}
	}
	if phin == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			philex.Error(phiErrorMessage(phistate, phitoken))
			Nerrs++
			if phiDebug >= 1 {
				__yyfmt__.Printf("%s", phiStatname(phistate))
				__yyfmt__.Printf(" saw %s\n", phiTokname(phitoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for phip >= 0 {
				phin = int(phiPact[phiS[phip].yys]) + phiErrCode
				if phin >= 0 && phin < phiLast {
					phistate = int(phiAct[phin]) /* simulate a shift of "error" */
					if int(phiChk[phistate]) == phiErrCode {
						goto phistack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if phiDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", phiS[phip].yys)
				}
				phip--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if phiDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", phiTokname(phitoken))
			}
			if phitoken == phiEofCode {
				goto ret1
			}
			phircvr.char = -1
			phitoken = -1
			goto phinewstate /* try again in the same state */
		}
	}

	/* reduction by production phin */
	if phiDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", phin, phiStatname(phistate))
	}

	phint := phin
	phipt := phip
	_ = phipt // guard against "declared and not used"

	phip -= int(phiR2[phin])
	// phip is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if phip+1 >= len(phiS) {
		nyys := make([]phiSymType, len(phiS)*2)
		copy(nyys, phiS)
		phiS = nyys
	}
	phiVAL = phiS[phip+1]

	/* consult goto table to find next state */
	phin = int(phiR1[phin])
	phig := int(phiPgo[phin])
	phij := phig + phiS[phip].yys + 1

	if phij >= phiLast {
		phistate = int(phiAct[phig])
	} else {
		phistate = int(phiAct[phij])
		if int(phiChk[phistate]) != -phin {
			phistate = int(phiAct[phig])
		}
	}
	// dummy call; replaced with literal code
	switch phint {

	case 1:
		phiDollar = phiS[phipt-1 : phipt+1]
//line parser/parser.y:53
		{
		}
	case 2:
		phiDollar = phiS[phipt-1 : phipt+1]
//line parser/parser.y:59
		{
			philex.(*lexer).processesOrFunctionsRes = append(philex.(*lexer).processesOrFunctionsRes, unexpandedProcessOrFunction{kind: PROCESS_DEF, proc: incompleteProcess{Body: phiDollar[1].form, Providers: []process.Name{{Ident: "root", IsSelf: false}}}})
		}
	case 3:
		phiDollar = phiS[phipt-1 : phipt+1]
//line parser/parser.y:63
		{
			philex.(*lexer).processesOrFunctionsRes = phiDollar[1].statements
		}
	case 4:
		phiDollar = phiS[phipt-1 : phipt+1]
//line parser/parser.y:69
		{
			phiVAL.statements = []unexpandedProcessOrFunction{phiDollar[1].common_type}
		}
	case 5:
		phiDollar = phiS[phipt-2 : phipt+1]
//line parser/parser.y:70
		{
			phiVAL.statements = append([]unexpandedProcessOrFunction{phiDollar[1].common_type}, phiDollar[2].statements...)
		}
	case 6:
		phiDollar = phiS[phipt-1 : phipt+1]
//line parser/parser.y:71
		{
			phiVAL.statements = []unexpandedProcessOrFunction{phiDollar[1].common_type}
		}
	case 7:
		phiDollar = phiS[phipt-2 : phipt+1]
//line parser/parser.y:72
		{
			phiVAL.statements = append([]unexpandedProcessOrFunction{phiDollar[1].common_type}, phiDollar[2].statements...)
		}
	case 8:
		phiDollar = phiS[phipt-1 : phipt+1]
//line parser/parser.y:73
		{
			phiVAL.statements = []unexpandedProcessOrFunction{phiDollar[1].common_type}
		}
	case 9:
		phiDollar = phiS[phipt-2 : phipt+1]
//line parser/parser.y:74
		{
			phiVAL.statements = append([]unexpandedProcessOrFunction{phiDollar[1].common_type}, phiDollar[2].statements...)
		}
	case 10:
		phiDollar = phiS[phipt-1 : phipt+1]
//line parser/parser.y:75
		{
			phiVAL.statements = []unexpandedProcessOrFunction{phiDollar[1].common_type}
		}
	case 11:
		phiDollar = phiS[phipt-2 : phipt+1]
//line parser/parser.y:76
		{
			phiVAL.statements = append([]unexpandedProcessOrFunction{phiDollar[1].common_type}, phiDollar[2].statements...)
		}
	case 12:
		phiDollar = phiS[phipt-1 : phipt+1]
//line parser/parser.y:77
		{
			phiVAL.statements = []unexpandedProcessOrFunction{phiDollar[1].common_type}
		}
	case 13:
		phiDollar = phiS[phipt-2 : phipt+1]
//line parser/parser.y:78
		{
			phiVAL.statements = append([]unexpandedProcessOrFunction{phiDollar[1].common_type}, phiDollar[2].statements...)
		}
	case 14:
		phiDollar = phiS[phipt-6 : phipt+1]
//line parser/parser.y:84
		{
			phiVAL.common_type = unexpandedProcessOrFunction{kind: PROCESS_DEF, proc: incompleteProcess{Body: phiDollar[6].form, Providers: phiDollar[3].names}}
		}
	case 15:
		phiDollar = phiS[phipt-8 : phipt+1]
//line parser/parser.y:86
		{
			phiVAL.common_type = unexpandedProcessOrFunction{kind: PROCESS_DEF, proc: incompleteProcess{Body: phiDollar[8].form, Type: phiDollar[6].sessionType, Providers: phiDollar[3].names}}
		}
	case 16:
		phiDollar = phiS[phipt-7 : phipt+1]
//line parser/parser.y:92
		{
			phiVAL.form = process.NewSend(phiDollar[2].name, phiDollar[4].name, phiDollar[6].name)
		}
	case 17:
		phiDollar = phiS[phipt-10 : phipt+1]
//line parser/parser.y:96
		{
			phiVAL.form = process.NewReceive(phiDollar[2].name, phiDollar[4].name, phiDollar[8].name, phiDollar[10].form)
		}
	case 18:
		phiDollar = phiS[phipt-6 : phipt+1]
//line parser/parser.y:98
		{
			phiVAL.form = process.NewSelect(phiDollar[1].name, process.Label{L: phiDollar[3].strval}, phiDollar[5].name)
		}
	case 19:
		phiDollar = phiS[phipt-5 : phipt+1]
//line parser/parser.y:100
		{
			phiVAL.form = process.NewCase(phiDollar[2].name, phiDollar[4].branches)
		}
	case 20:
		phiDollar = phiS[phipt-6 : phipt+1]
//line parser/parser.y:102
		{
			phiVAL.form = process.NewNew(phiDollar[1].name, phiDollar[4].form, phiDollar[6].form, types.UNKNOWN)
		}
	case 21:
		phiDollar = phiS[phipt-8 : phipt+1]
//line parser/parser.y:104
		{
			phiVAL.form = process.NewNew(process.Name{Ident: phiDollar[1].strval, Type: phiDollar[3].sessionType, IsSelf: false}, phiDollar[6].form, phiDollar[8].form, types.UNKNOWN)
		}
	case 22:
		phiDollar = phiS[phipt-7 : phipt+1]
//line parser/parser.y:106
		{
			phiVAL.form = process.NewNew(phiDollar[1].name, phiDollar[5].form, phiDollar[7].form, phiDollar[3].polarity)
		}
	case 23:
		phiDollar = phiS[phipt-9 : phipt+1]
//line parser/parser.y:108
		{
			phiVAL.form = process.NewNew(process.Name{Ident: phiDollar[1].strval, Type: phiDollar[3].sessionType, IsSelf: false}, phiDollar[7].form, phiDollar[9].form, phiDollar[5].polarity)
		}
	case 24:
		phiDollar = phiS[phipt-4 : phipt+1]
//line parser/parser.y:110
		{
			phiVAL.form = process.NewCall(phiDollar[1].strval, phiDollar[3].names, types.UNKNOWN)
		}
	case 25:
		phiDollar = phiS[phipt-5 : phipt+1]
//line parser/parser.y:112
		{
			phiVAL.form = process.NewCall(phiDollar[2].strval, phiDollar[4].names, phiDollar[1].polarity)
		}
	case 26:
		phiDollar = phiS[phipt-2 : phipt+1]
//line parser/parser.y:114
		{
			phiVAL.form = process.NewClose(phiDollar[2].name)
		}
	case 27:
		phiDollar = phiS[phipt-3 : phipt+1]
//line parser/parser.y:116
		{
			phiVAL.form = process.NewForward(phiDollar[2].name, phiDollar[3].name, types.UNKNOWN)
		}
	case 28:
		phiDollar = phiS[phipt-4 : phipt+1]
//line parser/parser.y:118
		{
			phiVAL.form = process.NewForward(phiDollar[3].name, phiDollar[4].name, phiDollar[1].polarity)
		}
	case 29:
		phiDollar = phiS[phipt-10 : phipt+1]
//line parser/parser.y:120
		{
			phiVAL.form = process.NewSplit(phiDollar[2].name, phiDollar[4].name, phiDollar[8].name, phiDollar[10].form, types.UNKNOWN)
		}
	case 30:
		phiDollar = phiS[phipt-11 : phipt+1]
//line parser/parser.y:122
		{
			phiVAL.form = process.NewSplit(phiDollar[2].name, phiDollar[4].name, phiDollar[9].name, phiDollar[11].form, phiDollar[7].polarity)
		}
	case 31:
		phiDollar = phiS[phipt-4 : phipt+1]
//line parser/parser.y:124
		{
			phiVAL.form = process.NewWait(phiDollar[2].name, phiDollar[4].form)
		}
	case 32:
		phiDollar = phiS[phipt-5 : phipt+1]
//line parser/parser.y:126
		{
			phiVAL.form = process.NewCast(phiDollar[2].name, phiDollar[4].name)
		}
	case 33:
		phiDollar = phiS[phipt-6 : phipt+1]
//line parser/parser.y:128
		{
			phiVAL.form = process.NewShift(phiDollar[1].name, phiDollar[4].name, phiDollar[6].form)
		}
	case 34:
		phiDollar = phiS[phipt-4 : phipt+1]
//line parser/parser.y:130
		{
			phiVAL.form = process.NewDrop(phiDollar[2].name, phiDollar[4].form)
		}
	case 35:
		phiDollar = phiS[phipt-3 : phipt+1]
//line parser/parser.y:132
		{
			phiVAL.form = phiDollar[2].form
		}
	case 36:
		phiDollar = phiS[phipt-4 : phipt+1]
//line parser/parser.y:134
		{
			phiVAL.form = process.NewPrint(phiDollar[2].name, phiDollar[4].form)
		}
	case 37:
		phiDollar = phiS[phipt-0 : phipt+1]
//line parser/parser.y:138
		{
			phiVAL.branches = nil
		}
	case 38:
		phiDollar = phiS[phipt-6 : phipt+1]
//line parser/parser.y:139
		{
			phiVAL.branches = []*process.BranchForm{process.NewBranch(process.Label{L: phiDollar[1].strval}, phiDollar[3].name, phiDollar[6].form)}
		}
	case 39:
		phiDollar = phiS[phipt-8 : phipt+1]
//line parser/parser.y:140
		{
			phiVAL.branches = append(phiDollar[1].branches, process.NewBranch(process.Label{L: phiDollar[3].strval}, phiDollar[5].name, phiDollar[8].form))
		}
	case 40:
		phiDollar = phiS[phipt-1 : phipt+1]
//line parser/parser.y:143
		{
			phiVAL.names = []process.Name{phiDollar[1].name}
		}
	case 41:
		phiDollar = phiS[phipt-3 : phipt+1]
//line parser/parser.y:144
		{
			phiVAL.names = append([]process.Name{phiDollar[1].name}, phiDollar[3].names...)
		}
	case 42:
		phiDollar = phiS[phipt-0 : phipt+1]
//line parser/parser.y:146
		{
			phiVAL.names = nil
		}
	case 43:
		phiDollar = phiS[phipt-1 : phipt+1]
//line parser/parser.y:147
		{
			phiVAL.names = []process.Name{phiDollar[1].name}
		}
	case 44:
		phiDollar = phiS[phipt-3 : phipt+1]
//line parser/parser.y:148
		{
			phiVAL.names = append([]process.Name{phiDollar[1].name}, phiDollar[3].names...)
		}
	case 45:
		phiDollar = phiS[phipt-0 : phipt+1]
//line parser/parser.y:151
		{
			phiVAL.names = nil
		}
	case 46:
		phiDollar = phiS[phipt-1 : phipt+1]
//line parser/parser.y:152
		{
			phiVAL.names = []process.Name{phiDollar[1].name}
		}
	case 47:
		phiDollar = phiS[phipt-3 : phipt+1]
//line parser/parser.y:153
		{
			phiVAL.names = append([]process.Name{phiDollar[1].name}, phiDollar[3].names...)
		}
	case 48:
		phiDollar = phiS[phipt-0 : phipt+1]
//line parser/parser.y:156
		{
			phiVAL.names = nil
		}
	case 49:
		phiDollar = phiS[phipt-2 : phipt+1]
//line parser/parser.y:157
		{
			phiVAL.names = phiDollar[2].names
		}
	case 50:
		phiDollar = phiS[phipt-1 : phipt+1]
//line parser/parser.y:161
		{
			phiVAL.names = []process.Name{phiDollar[1].name}
		}
	case 51:
		phiDollar = phiS[phipt-3 : phipt+1]
//line parser/parser.y:162
		{
			phiVAL.names = append([]process.Name{phiDollar[1].name}, phiDollar[3].names...)
		}
	case 52:
		phiDollar = phiS[phipt-1 : phipt+1]
//line parser/parser.y:167
		{
			phiVAL.name = process.Name{Ident: phiDollar[1].strval, IsSelf: false}
		}
	case 53:
		phiDollar = phiS[phipt-3 : phipt+1]
//line parser/parser.y:169
		{
			phiVAL.name = process.Name{Ident: phiDollar[1].strval, Type: phiDollar[3].sessionType, IsSelf: false}
		}
	case 54:
		phiDollar = phiS[phipt-1 : phipt+1]
//line parser/parser.y:171
		{
			phiVAL.name = process.Name{IsSelf: true}
		}
	case 55:
		phiDollar = phiS[phipt-1 : phipt+1]
//line parser/parser.y:172
		{
			phiVAL.name = process.Name{Ident: phiDollar[1].strval, IsSelf: false}
		}
	case 56:
		phiDollar = phiS[phipt-2 : phipt+1]
//line parser/parser.y:176
		{
			phiVAL.common_type = unexpandedProcessOrFunction{kind: ASSUMING_DEF, assumedFreeNameTypes: phiDollar[2].names}
		}
	case 57:
		phiDollar = phiS[phipt-7 : phipt+1]
//line parser/parser.y:181
		{
			phiVAL.common_type = unexpandedProcessOrFunction{kind: FUNCTION_DEF, function: process.FunctionDefinition{FunctionName: phiDollar[2].strval, Parameters: phiDollar[4].names, Body: phiDollar[7].form, UsesExplicitProvider: false}}
		}
	case 58:
		phiDollar = phiS[phipt-9 : phipt+1]
//line parser/parser.y:183
		{
			phiVAL.common_type = unexpandedProcessOrFunction{kind: FUNCTION_DEF, function: process.FunctionDefinition{FunctionName: phiDollar[2].strval, Parameters: phiDollar[4].names, Body: phiDollar[9].form, Type: phiDollar[7].sessionType, UsesExplicitProvider: false}}
		}
	case 59:
		phiDollar = phiS[phipt-8 : phipt+1]
//line parser/parser.y:186
		{
			phiVAL.common_type = unexpandedProcessOrFunction{kind: FUNCTION_DEF, function: process.FunctionDefinition{
				FunctionName:         phiDollar[2].strval,
				Parameters:           phiDollar[5].names,
				Body:                 phiDollar[8].form,
				UsesExplicitProvider: true,
				ExplicitProvider:     process.Name{Ident: phiDollar[4].strval, IsSelf: true},
				// Type: $6,
			}}
		}
	case 60:
		phiDollar = phiS[phipt-10 : phipt+1]
//line parser/parser.y:197
		{
			phiVAL.common_type = unexpandedProcessOrFunction{kind: FUNCTION_DEF, function: process.FunctionDefinition{
				FunctionName:         phiDollar[2].strval,
				Parameters:           phiDollar[7].names,
				Body:                 phiDollar[10].form,
				UsesExplicitProvider: true,
				ExplicitProvider:     process.Name{Ident: phiDollar[4].strval, IsSelf: true},
				Type:                 phiDollar[6].sessionType}}
		}
	case 61:
		phiDollar = phiS[phipt-4 : phipt+1]
//line parser/parser.y:207
		{
			phiVAL.common_type = unexpandedProcessOrFunction{kind: TYPE_DEF, session_type: types.SessionTypeDefinition{Name: phiDollar[2].strval, SessionType: phiDollar[4].sessionType}}
		}
	case 62:
		phiDollar = phiS[phipt-1 : phipt+1]
//line parser/parser.y:211
		{
			phiVAL.sessionType = types.NewLabelType(phiDollar[1].strval)
		}
	case 63:
		phiDollar = phiS[phipt-1 : phipt+1]
//line parser/parser.y:213
		{
			phiVAL.sessionType = types.NewUnitType()
		}
	case 64:
		phiDollar = phiS[phipt-4 : phipt+1]
//line parser/parser.y:215
		{
			phiVAL.sessionType = types.NewSelectType(phiDollar[3].sessionTypeAlt)
		}
	case 65:
		phiDollar = phiS[phipt-4 : phipt+1]
//line parser/parser.y:217
		{
			phiVAL.sessionType = types.NewBranchCaseType(phiDollar[3].sessionTypeAlt)
		}
	case 66:
		phiDollar = phiS[phipt-3 : phipt+1]
//line parser/parser.y:219
		{
			phiVAL.sessionType = types.NewSendType(phiDollar[1].sessionType, phiDollar[3].sessionType)
		}
	case 67:
		phiDollar = phiS[phipt-3 : phipt+1]
//line parser/parser.y:221
		{
			phiVAL.sessionType = types.NewReceiveType(phiDollar[1].sessionType, phiDollar[3].sessionType)
		}
	case 68:
		phiDollar = phiS[phipt-3 : phipt+1]
//line parser/parser.y:223
		{
			phiVAL.sessionType = phiDollar[2].sessionType
		}
	case 69:
		phiDollar = phiS[phipt-3 : phipt+1]
//line parser/parser.y:226
		{
			phiVAL.sessionTypeAlt = []types.BranchOption{*types.NewBranchOption(phiDollar[1].strval, phiDollar[3].sessionType)}
		}
	case 70:
		phiDollar = phiS[phipt-5 : phipt+1]
//line parser/parser.y:227
		{
			phiVAL.sessionTypeAlt = append([]types.BranchOption{*types.NewBranchOption(phiDollar[1].strval, phiDollar[3].sessionType)}, phiDollar[5].sessionTypeAlt...)
		}
	case 71:
		phiDollar = phiS[phipt-1 : phipt+1]
//line parser/parser.y:230
		{
			phiVAL.polarity = types.POSITIVE
		}
	case 72:
		phiDollar = phiS[phipt-1 : phipt+1]
//line parser/parser.y:231
		{
			phiVAL.polarity = types.NEGATIVE
		}
	case 73:
		phiDollar = phiS[phipt-4 : phipt+1]
//line parser/parser.y:235
		{
			phiVAL.common_type = unexpandedProcessOrFunction{
				kind: EXEC_DEF,
				proc: incompleteProcess{Body: process.NewCall(phiDollar[2].strval, []process.Name{}, types.UNKNOWN)}}
		}
	case 74:
		phiDollar = phiS[phipt-5 : phipt+1]
//line parser/parser.y:239
		{
			phiVAL.common_type = unexpandedProcessOrFunction{
				kind: EXEC_DEF,
				proc: incompleteProcess{Body: process.NewCall(phiDollar[3].strval, []process.Name{}, phiDollar[2].polarity)}}
		}
	}
	goto phistack /* stack new state and value */
}
